name: review_app
description: "新しいFlutterプロジェクト"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  characters: ^1.3.0
  cupertino_icons: ^1.0.8
  diacritic: ^0.1.2
  flutter:
    sdk: flutter
  flutter_image_compress: ^2.1.0
  flutter_rating_bar: ^4.0.1
  flutter_secure_storage: ^9.2.4
  google_sign_in: ^6.3.0
  http: ^1.1.0
  image_picker: ^0.8.7+5
  path: ^1.8.3
  path_provider: ^2.1.2
  provider: ^6.0.6
  shared_preferences: ^2.2.2
  sliding_up_panel: ^2.0.0
  sqflite: ^2.3.2
  fl_chart: ^0.69.0
  uuid: ^4.3.3
  crypto: ^3.0.3
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/


flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/splash.png
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: center

    # ★ Android 12 対策（これがないと青くなる）
  android_12:
    color: "#FFFFFF"
    image: assets/images/splash.png